### ISSUE TITLE
Compose Containers

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/constate#10]
```jsx
const TodosContainer = props => (
  <Container initialState={{ todos: [] }}  />
);

const VisibilityContainer = props => (
  <Container initialState={{ visibleItems: [] }} />
);

<Container compose={[TodosContainer, VisibilityContainer]}>
  {({ todos, visibleItems }) => ...}
</Container>
```

**Comment by codyaverett** [comment]
@diegohaz 
I totally have a use case for something like this right now.  We have a group of components that needs state vars from separate containers, so right now we have a container sandwich.

How do you think context could be handled?
e.g. I have two containers with different context that need to be composed together.


```
<Container1 context="foo">
    {(fooThing) => (
        <Container2 context="bar">
            {(barThing) => (
                <div>{fooThing} and {barThing}</div>
            )
        </Container2>
    )
</Container1>
```

**Comment by diegohaz** [comment]
@codyaverett 

I also had some use cases like that.

When I wrote this issue, one idea I had was to merge both containers to work like a single one (similar to [Composing](https://github.com/diegohaz/constate#composing)), which wouldn't work if you wanted to have different contexts. But so far I didn't need it.

Your example is usually called "render props callback hell". If you put that on Google, you'll find interesting things, including an advise from our prophet: https://github.com/facebook/react/issues/12664#issuecomment-383200601

I sincerely don't know the best way to handle that. I'm open for ideas. For now, I'm sticking with callback hell. XD

**Comment by codyaverett** [comment]
@diegohaz 
React-powerplug has a nice pattern.  WDYT?
https://github.com/renatorib/react-powerplug#composing-components
