### ISSUE TITLE
Limit to the number of split values?

### ISSUE THREAD

**Issue by meisterpeeps** [diegohaz/constate#109]
I'm curious if there is a limit to the number of split values constate can return?
I've got 14, and around the 10th item in the destructured array it returns a Function Component type when it should be a React.Dispatch type.

**Comment by weltenwort** [comment]
That limit seems to exist in the type definition, but not in the implementation:

https://github.com/diegohaz/constate/blob/633f7f75a2e30f3ee036645d9e09f6026c734a77/src/types.ts#L32-L50

**Comment by diegohaz** [comment]
What @weltenwort said! I didn't expect people splitting more than 10 values. But feel free to send a PR enhancing the types (even if it's just adding more lines to the current type).
