### ISSUE TITLE
Simple Package

### ISSUE THREAD

**Issue by Aslemammad** [diegohaz/constate#115]
Hey constate team👋, I created A similar and simpler package named [Contextism](https://github.com/Aslemammad/contextism), I'll be happy if you check it, help me with developing it and mention it if you liked. Thanks.

**Comment by diegohaz** [comment]
Hello! That's a cool project! It looks very similar to Redux. My suggestion is to add a section in the README comparing it with other solutions.

There's a reason why Redux didn't use React Context (mostly because of performance), and I'd be curious to know how your library deals with it.

**Comment by Aslemammad** [comment]
Thanks for your idea.
