### ISSUE TITLE
Allow to invoke useCounter hook with arguments

### ISSUE THREAD

**Issue by pf-costa** [diegohaz/constate#119]
First of all, thanks for the lib, love the overall concept. 

Considering the hook **useCounter** used in the tests, shouldn't it be allowed to specify the initialCount? In my use case, I want to invoke my hooks with arguments.

![image](https://user-images.githubusercontent.com/63285433/93757128-2046d780-fbfe-11ea-87b7-a0f3dfa85910.png)

**Comment by diegohaz** [comment]
You have to pass it as a prop to the Provider component.

**Comment by pf-costa** [comment]
Thanks for the clarification!
