### ISSUE TITLE
Is it possible to have a ref to the Provider?

### ISSUE THREAD

**Issue by awkpagong** [diegohaz/constate#120]
Is it possible to get a ref to the `Provider` and then use that ref in the hook?

For example, would it be possible to do something like this?:

```
function useValueWithRef({ initialValue }, ref) {
   const [value, setValue] = useState(initialValue);
   
   useImperativeHandle(ref, () => ({ setValue }));

   return { setValue, value };
}

const [ValueProvider, useValueContext] = constate(useValueWithRef);

function App() {
   const ref = useRef();

   useEffect(() => {
      setTimeout(() => {
         ref.current.setValue('b');
      }, 2000);
   }, []);

   return (
      <ValueProvider ref={ref} initialValue="a">
        {/* child components... */}
      </ValueProvider>
   );
}
```

**Comment by diegohaz** [comment]
I've never seen that. Maybe something like this?

```jsx
function useValueWithRef({ providerRef }) {
  ...
}

...

<ValueProvider providerRef={ref} />
```

**Comment by weltenwort** [comment]
I've come across this a few times while working on https://github.com/elastic/kibana. The solution I used was to decompose the `App`, providers and content into several components so the context value can be accessed via the hook as usual:

```typescript
const App = () => (
  <AppProviders initialValue="a">
    <AppEffects />
    <AppContent />
  </AppProviders>
)

const AppProviders = ({ children, initialValue }) => {
  <ValueProvider initialValue={initialValue}>
    {children}
  </ValueProvider>
}

const AppEffects = () => {
  const [, setValue] = useValueContext();

  useEffect(() => {
    setTimeout(() => {
       setValue('b');
    }, 2000);
  }, [setValue]);
}
```

I find that pretty readable without the need for a more complex API. @awkpagong, could that work for you?

**Comment by awkpagong** [comment]
> I've never seen that. Maybe something like this?
> 
> ```js-jsx
> function useValueWithRef({ providerRef }) {
>   ...
> }
> 
> ...
> 
> <ValueProvider providerRef={ref} />
> ```

@diegohaz thanks for the suggestion. I will try that. And thanks for all your amazing work on this package!

**Comment by diegohaz** [comment]
I still don't understand the use case. But, If @weltenwort's solution solves your problem, it's preferable.

**Comment by awkpagong** [comment]
@diegohaz ok I will try @weltenwort's suggestion then. It's a bit more verbose, but I agree it will keep the API simple. Thanks for the suggestions guys!
