### ISSUE TITLE
Demo for Complex Set State

### ISSUE THREAD

**Issue by hariria** [diegohaz/constate#123]
Does anyone have a typescript demo of how constate could be used to keep track of a more complex state. The demos provided are quite basic and intuitive for something like a counter with useIncrement. But are there any examples of how this could be used on something that stores a much more complex state? Your help would be greatly appreciated!

**Comment by diegohaz** [comment]
If you can find a complex example using React hooks, you already have a complex constate example:
```ts
import constate from "constate";
import { useComplexCustomHook } from "any-library";

const [Provider, useComplexContext] = constate(useComplexCustomHook);
```

**Comment by weltenwort** [comment]
@hariria It's not a demo as such, but we've used it for some pretty complex state in Kibana. Maybe that can serve as examples for your purposes.

https://github.com/elastic/kibana/blob/6110ef82a3a0537a82738c3f039d850772f24306/x-pack/plugins/infra/public/containers/logs/log_analysis/modules/log_entry_rate/use_log_entry_rate_module.tsx
