### ISSUE TITLE
How can i use overloading with constate?

### ISSUE THREAD

**Issue by polRk** [diegohaz/constate#124]
```tsx
function useNavigation(): NavigationRoutes
function useNavigation(route: keyof NavigationRoutes): NavigationRoute
function useNavigation(route?: keyof NavigationRoutes): NavigationRoute | NavigationRoutes {}

export const [NavigationProvider, useNavigationContext] = constate(
  useNavigation
)
```

**Comment by renatobenks** [comment]
what do you mean by overloading? 🤔

**Comment by polRk** [comment]
@renatobenks Example

```typescript
const {routes} = useNavigationContext() // should return array of routes

const {title, description} = useNavigationContext('home') // should return information about single route
```

**Comment by diegohaz** [comment]
@polRk Could you please fork https://codesandbox.io/s/github/diegohaz/constate/tree/master/examples/typescript?module=/App.tsx and add your case there so we can inspect it?

**Comment by polRk** [comment]
@diegohaz  https://codesandbox.io/s/blazing-cdn-517pf?file=/index.tsx

**Comment by diegohaz** [comment]
I see. I don't think there's a way to achieve what you want with Constate since the `route` parameter should be passed using the Provider, not the hook. Constate would be useful only for getting all the routes in this case.
