### ISSUE TITLE
Types are not inferred properly

### ISSUE THREAD

**Issue by timkindberg** [diegohaz/constate#144]
My hook has properly inferred types, see here, this is the types that my hook has as seen by the Typescript Service.

My hook:
![image](https://user-images.githubusercontent.com/168046/124207653-f9ce9a80-dab3-11eb-9a5e-2e509d3c5a7c.png)

But after passing through `constate`, the new Provider and Hook that are created have no inferred types, so I'm not getting any TS help/completions anywhere. 

Constate's hook:
![image](https://user-images.githubusercontent.com/168046/124207712-1cf94a00-dab4-11eb-95c4-87e04d48b522.png)

Return from constate hook (no types):
![image](https://user-images.githubusercontent.com/168046/124207887-6ba6e400-dab4-11eb-872d-964663603ef5.png)

**Comment by diegohaz** [comment]
This should work. Can you create a CodeSandbox demonstrating the issue?

**Comment by timkindberg** [comment]
https://codesandbox.io/s/constatetypeinference-eheo9

Hmm it works there... and it works in VS Code... damn maybe a Jetbrains bug. Are you using like a really new TS feature or something?

![image](https://user-images.githubusercontent.com/168046/124215816-cb0bf080-dac2-11eb-8676-a16961da2cab.png)

**Comment by timkindberg** [comment]
I made a Jetbrains issue: https://youtrack.jetbrains.com/issue/WEB-51538

if you can provide any additional context or guesses on that ticket please feel free.

**Comment by timkindberg** [comment]
Ok so not sure if you are open to this, but if you rewrite the types like this, then it works in PyCharm and VS Code, IMO it's a bit cleaner too :)

```ts
import * as React from "react";
declare type Selector<Value> = (value: Value) => any;
declare type SelectorHooks<Selectors> = {
    [K in keyof Selectors]: () => Selectors[K] extends (...args: any) => infer R ? R : never;
};

// Here's the change...
// Removed the Hooks type and just did the `extends` check right here
declare type ConstateTuple<Props, Value, Selectors extends Selector<Value>[]> = Selectors["length"] extends 0
  ? [React.FC<Props>, () => Value]
  : [React.FC<Props>, ...SelectorHooks<Selectors>];

declare function constate<Props, Value, Selectors extends Selector<Value>[]>(useValue: (props: Props) => Value, ...selectors: Selectors): ConstateTuple<Props, Value, Selectors>;
export default constate;
```

**Comment by timkindberg** [comment]
Hmm ok that was when I just hacked them real quick from the node_modules folder... but I've got a fork of constate open and I'm having trouble getting the types to behave...

Oddly, the types are working properly in PyCharm when I am in YOUR project's index.ts file:
![image](https://user-images.githubusercontent.com/168046/124221420-c39e1480-dacd-11eb-9550-99c0e4fa00ea.png)

Maybe it's something to do with how the types were exported??

**Comment by timkindberg** [comment]
🤦  I had TS 3 running in PyCharm in my project... that's why it worked in your project... cause it picked up the right version. Easy fix. Sorry for the distraction.
