### ISSUE TITLE
Warn about ignored initialState

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/constate#30]
Since the last version, when a Container has `context`, we're ignoring `initialState` after it's been set. We should warn when someone tries to set further `initialState`.

**Comment by billykwok** [comment]
I'm working on a couple of open issues in this repo. For this one, I would like to confirm your intention. Which of the following two cases do you mean?

When `<Container />` has `context` defined,
1) its parent `<Provider />`'s `initialState` should not be set further, or
2) its own `initialState` should not be set both initially and further?

**Comment by diegohaz** [comment]
Hey @billykwok,

In this example, `count` should be `0`:
```jsx
<Provider initialState={{ foo: { count: 0 } }}>
  <Container initialState={{ count: 1 }} context="foo" />
  <Container initialState={{ count: 2 }} context="foo" />
  <Container initialState={{ count: 3 }} context="foo" />
</Provider>
```

In this example, `count` should be `2`:
```jsx
<Provider>
  <Container context="foo" />
  <Container initialState={{ count: 2 }} context="foo" />
  <Container initialState={{ count: 3 }} context="foo" />
</Provider>
```

So, in short, only the first mounted `initialState` for that context should be used. The others should be ignored.

My intention with this issue was to warn when an `initialState` is ignored. In the latter example, the last `<Container initialState={{ count: 3 }} context="foo" />` should warn.

But I'm not sure if it's possible to identify whether one is actually passing a different `initialState` without heavy work arounds.

And, actually, it has a minor bug.

----

Let me explain how this works internally...

When `<Container />` has `context`, we pass some additional props to `InnerContainer`:
https://github.com/diegohaz/constate/blob/87a065dbaebb8b2762f646f685aae8548976ec0b/src/Container.tsx#L170-L183

As you can see, `state` is the state for that particular context, which is stored in `Provider` and grabbed by `Consumer`.

Inside `InnerContainer`'s `constructor`, we check if `state` already exists. If not, we use `setContextState` to assign the `initialState` passed to `<Container />` into context state:
https://github.com/diegohaz/constate/blob/87a065dbaebb8b2762f646f685aae8548976ec0b/src/Container.tsx#L40-L47

In theory, that `&& !state` should prevent subsequent `initialState`s. But, the reality is that React `setState` (which is used by `setContextState`) works asynchronously, while component mounting is synchronous.

When React mounts the last `<Container initialState={{ count: 3 }} context="foo" />`, `state` hasn't been set yet due to the async nature of `setState`.

It will end up being `{ count: 2 }` because we're always overriding `initialState` with `currentState`:
https://github.com/diegohaz/constate/blob/87a065dbaebb8b2762f646f685aae8548976ec0b/src/Container.tsx#L43

That check will only work for components mounted after the first render loop (for example, they can be mounted after a user interaction, like a route change).

The problem is that in the first render loop, if a Container sets an `initialState` with a different key, it'll not be ignored.

Here is an example: https://codesandbox.io/s/380o33wy16

**Comment by billykwok** [comment]
Why should we allow `initialState` in `Container` in the first place? The only use case I could think of is to lazily initialize a global state when a component is dynamically loaded (i.e. The `<Delay />` component in your Code Sandbox example).

My opinion is that, if we already know the initial state of a context in the first render loop, shouldn't we directly put it in the `Provider`'s `initialState` prop? This makes much more sense because `initialState` should not depend on whether a `Container` is the first one to be rendered. Having multiple sync `Container`s with `initialState` seems more like an antipattern to me than a feature that we should support. People who really want to do this should manage the agreement of initialState themselves instead of relying on a beautiful and lightweight library to give an opinionated solution.

What is your thought on that?

**Comment by diegohaz** [comment]
> Why should we allow initialState in Container in the first place?

> If we already know the initial state of a context in the first render loop, shouldn't we directly put it in the Provider's initialState prop?

Besides being necessary when `Container` has no `context` (ie. local state), it allows us to easily convert it into global state when necessary. If we had to remove `initialState` from `Container` and put it into `Provider` every time, this would defeat the purpose of this library.

> This makes much more sense because initialState should not depend on whether a Container is the first one to be rendered. Having multiple sync Containers with initialState seems more like an antipattern to me than a feature that we should support.

I totally agree.

> What is your thought on that?

This is only a problem if people use different `initialState`s on the same `context`s. If they abstract containers into their own files and don't accept initial state as props, it doesn't happen:
```js
const PostsContainer = props => (
  <Container {...props} initialState={{ posts: [] }} />
);
```
```jsx
<PostsContainer context="articles">
  {({ posts }) => (
    ...
  )}
</PostsContainer>
```

In the implementations I'm seeing on GitHub and CodeSandbox, it seems to not be a problem for most people. So maybe just a note in the README should be enough.

**Comment by billykwok** [comment]
Sorry, perhaps I didn't make it clear. I also think that having `initialState` prop is necessary when `Container` has no context (ie. local state), and we should definitely keep the `initialState` prop for the use cases of context-less `Container` and lazy `Container`.

But I'm a bit skeptical about why removing `initialState` from `Container` and put it into `Provider` every time is a bad thing and defeat the purpose of this library. After all, it is just a matter of CMD-X or CMD-C. And the benefit of keeping only one `initialState` for each context is quite significant - a much cleaner, more readable and errorproof codebase.

I am not sure whether we actually share the same thought. To make it clearer, I suggest that, in README, under the `context` prop documentation of `Container`, we add the following note.
> In general, when multiple `Container`s with the same `context` are used, the `initialState` prop of all related `Container`s should be moved to the global `Provider` component. This can avoid unwanted overriding of initial states and maintain a single source of truth. However, `initialState` is allowed in `Container` with `context` prop, when there is a strong reason to make the initialization of a global state local, for example, lazy initialization of global state when the first local consumer component is loaded.
