### ISSUE TITLE
Context and Server Side Rendering

### ISSUE THREAD

**Issue by codyaverett** [diegohaz/constate#38]
One of our project's GatsbyJS server side rendering seems to have some issues with finding the shape of state during build.

**Example Snippet**

```
export const SharedContainer: ComposableContainer<State, Actions, {}, Effects> = props => {
    return <Container initialState={initialState} effects={effects} actions={actions} context="myContextString" {...props} />;
};
```

**Gatsby Build error**

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  302 |             mountContainer = _ref.mountContainer;
  303 |         return createElement(InnerContainer, _extends({}, _this4.props, {
> 304 |           state: state[context],
      | ^
  305 |           setContextState: setContextState,
  306 |           mountContainer: mountContainer
  307 |         }));


  WebpackError: TypeError: Cannot read property 'myContextString' of undefined
```

The link in the error describes common pitfalls of SSR in gatsby.
e.g. `window` object is missing, either mockup window or wrap the code in a conditional so that it only runs if the object is truthy.
 
Running the app in dev mode does not have this issue. (Not SSR)

I'm trying to figure out how to get around this.  I'd like to not have to mock out the state of the app and just use context as is, but i'm not sure if that is possible at this point.

**Comment by diegohaz** [comment]
The error seems to be on this line:
https://github.com/diegohaz/constate/blob/a548d72e576ca511fa15d0e2d3d5fb0c86e9fb9d/src/Container.tsx#L168

That `state` comes directly from `Provider` and it's set there in the constructor:
https://github.com/diegohaz/constate/blob/a548d72e576ca511fa15d0e2d3d5fb0c86e9fb9d/src/Provider.tsx#L63

Have you wrapped your app with `Provider`?

Maybe the solution is to add `state: {}` here:
https://github.com/diegohaz/constate/blob/a548d72e576ca511fa15d0e2d3d5fb0c86e9fb9d/src/Context.ts#L17

**Comment by diegohaz** [comment]
I think that's OK. Do we really need `Partial` there?

**Comment by codyaverett** [comment]
As I see it, it's either we have it like this as a partial, or we'd also need to define setContextState, and mountContainer in that createContext Call.

```
const Context = React.createContext<ContextState>({ state: {}, mountContainer: (...mountContainerParams) => void, mountContainer: { ...mountContainerProps } });
```

**Comment by diegohaz** [comment]
I guess we can define `setContextState` and `mountContainer` as optionals.
