### ISSUE TITLE
Build errors Unexpected token

### ISSUE THREAD

**Issue by codyaverett** [diegohaz/constate#39]
Was going to go through some local dev cycles with npm link to further troubleshoot #38 and ran into some issues building constate locally. 

**Env**
OSX 10.13.6
node v8.11.2
npm v6.4.0 

**Steps to reproduce**
run `npm i`
run `npm run build`

**Error Output**
```npm run build

> constate@0.8.0 prebuild /directory/constate
> npm run clean


> constate@0.8.0 clean /directory/constate
> rimraf dist


> constate@0.8.0 build /directory/constate
> tsc --emitDeclarationOnly && rollup -c


src/index.ts → dist/constate.cjs.js, dist/constate.es.js...
(node:8176) Warning: N-API is an experimental feature and could change at any time.
[!] Error: Unexpected token
src/types.ts (3:7)
1: import * as React from "react";
2:
3: export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
          ^
4:
5: export type Dictionary<T> = { [key: string]: T };

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! constate@0.8.0 build: `tsc --emitDeclarationOnly && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the constate@0.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    /directory/.npm/_logs/2018-08-28T19_41_13_671Z-debug.log
```

Starting to wonder if it's just me 😅

**Comment by diegohaz** [comment]
Weird. It shouldn't be a problem. But can you try to use `yarn` instead of `npm`?

**Comment by diegohaz** [comment]
Hmm, it seems to be related to `rollup-babel-plugin@4.0.0`.

If you use `yarn` (which has locked to `v4.0.0-beta.8`) or update it to `"rollup-plugin-babel": "4.0.0-beta.8"` (remove `ˆ`) in package.json, it works.

**Comment by diegohaz** [comment]
I believe it's fixed. Can you try again, @codyaverett?

**Comment by codyaverett** [comment]
Yeah it's working great now. Thx @diegohaz
