### ISSUE TITLE
Subscription prop

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/constate#42]
```jsx
<Container
  initialState={{ foo: "foo", bar: "bar" }}
  subscription={{ foo: true }}
/>
```
It will be rendered only if `foo` has changed. Inspired by https://github.com/final-form/react-final-form#subscription-fieldsubscription

**Comment by billykwok** [comment]
Is the `shouldUpdate` prop in `Container` good enough for this use case? Other than than being a syntax shortcut, what benefits would it bring? I just personally think that `shouldUpdate` is clearer and short enough.

**Comment by diegohaz** [comment]
I guess the first case using `shouldUpdate` would look like this:
```jsx
<Container
  initialState={{ foo: "foo", bar: "bar" }}
  shouldUpdate={({ state, nextState }) => state.foo !== nextState.foo}
/>
```

But it can get more complex:
```jsx
// subscribe to "a", "b" and "c.b"
<Container
  initialState={{ a: "a", b: "b", c: { a: "a", b: "b" }, d: "d" }}
  shouldUpdate={({ state, nextState }) => (
    state.a !== nextState.a ||
    state.b !== nextState.b ||
    state.c.b !== nextState.c.b
  )}
/>

// or
<Container
  initialState={{ a: "a", b: "b", c: { a: "a", b: "b" }, d: "d" }}
  shouldUpdate={({ state, nextState }) => (
    state.c.a === nextState.c.a &&
    state.d === nextState.d
  )}
/>
```

The case above with `subscription`:
```jsx
// subscribe to "a", "b" and "c.b"
<Container
  initialState={{ a: "a", b: "b", c: { a: "a", b: "b" }, d: "d" }}
  subscription={{ a: true, b: true, "c.b": true }}
/>

// or
<Container
  initialState={{ a: "a", b: "b", c: { a: "a", b: "b" }, d: "d" }}
  subscription={{ "c.a": false, d: false }}
/>
```

The problem with `shouldUpdate` is that it can be hard to read and reason about. At the same time, we need to keep it as a low level API.

But, in the end, it depends on how often people would need something as `subscription`. For [`pure`](https://github.com/diegohaz/constate#pure), for example, I was using it almost everywhere (I even considered making it `true` by default, but it could have some silent unintended side effects), so it was worthing creating a prop for it.

The only situation I really wanted this `subscription` was when I was building a complex Form Container.
