### ISSUE TITLE
No cache in selectors, <Container /> performance issues in huge projects

### ISSUE THREAD

**Issue by Mati365** [diegohaz/constate#49]
Hi,

as I can see in:
https://github.com/diegohaz/constate/blob/master/src/Container.tsx#L152

there is no cache for selectors and every time is rendered it maps `actions`, `effect`, `selectors`. I think that large amount of actions in bigger projects and mapping them inside each `<Container>` render cycle will dramatically decrease overall app performance.

So question is:
- selector cache will be available in future releases?
- method mapping will be moved to something that is <Consumer /> parent?

For now - project is unusable for project that are larger than `Todo app`.

**Comment by diegohaz** [comment]
Thank you for the feedback @Mati365. I guess those are no longer issues in `v1`. I'm also working on benchmark stuff to guarantee that it's fast.
