### ISSUE TITLE
Accessing actions, effects and selectors from within

### ISSUE THREAD

**Issue by weltenwort** [diegohaz/constate#50]
Currently the actions, effects, selectors and lifecycle methods like `onMount`, `onUpdate` and `onUnmount` only have access to `state` and `setState`.

Making bound versions of their siblings available within these functions would enable more use-cases and promote code re-use.

## Example Use-case

The use-case below shows several interesting characteristics:

* the request tracking code is encapsulated in the action and the selector
* the initial loading can be triggered via the `onMount` handler

```typescript
// one of the actions
const updateRequestStatus = (status: 'loading' | 'loaded' | 'failed') => (state: State) => ({
  ...state,
  requestHistory: [
    ...state.requestHistory,
    {
      status,
      time: Date.now(),
    },
  ],
});

// one of the selectors
const isLoading = () => ({ requestHistory }: State) => (
  requestHistory.length > 0
    ? requestHistory[requestHistory.length - 1].status === 'loading'
    : false
)

// one of the effects
const loadFromServer = (id: string) => ({ actions, selectors, state }) => {
  if (selectors.isLoading()) {
    return
  }

  actions.updateRequestStatus('loading');
  fetch(`${state.basepath}/my-rest-route/${id}`)
    .then(result => actions.updateRequestStatus('loaded'));
}

// the onMount handler
const onMount: OnMount<State> = ({ effects, state }) => {
  effects.loadFromServer(state.someId);
}
```

While the first aspect can be achieved in a different way (encapsulate in external update functions), triggering effects on mount currently requires many contortions to achieve.

Would you be interested in adding these features or would you accept PRs to that extent?

**Comment by diegohaz** [comment]
Thank you for the suggestion @weltenwort. I actually like the idea, but I didn't want to make the API more unnecessarily complex and harder to mock if there were other ways to do that.

I re-written your code with the approach I currently use to achieve the same result. Let me know what you think.
```ts
// one of the actions
const updateRequestStatus = (status: 'loading' | 'loaded' | 'failed') => (state: State) => ({
  ...state,
  requestHistory: [
    ...state.requestHistory,
    {
      status,
      time: Date.now(),
    },
  ],
});

// one of the selectors
const isLoading = () => ({ requestHistory }: State) => (
  requestHistory.length > 0
    ? requestHistory[requestHistory.length - 1].status === 'loading'
    : false
)

// one of the effects
const loadFromServer = (id: string) => ({ state, setState }) => {
  if (isLoading()(state)) {
    return;
  }

  setState(updateRequestStatus('loading'));

  fetch(`${state.basepath}/my-rest-route/${id}`)
    .then(result => setState(updateRequestStatus('loaded')));
}

// the onMount handler
const onMount: OnMount<State> = props => {
  loadFromServer(props.state.someId)(props);
}
```

That's a simplistic example. [Here](https://github.com/reakit/reakit/blob/5a65f9c7e00a872a7795bf4eea60833a8cbe7e73/packages/reakit/src/Step/StepContainer.tsx) you can see more real world examples.

**Comment by weltenwort** [comment]
Trying this pattern out a bit, I can say that it seems to work. One of the remaining issues, though, is that by not using functions bound to the container, the `type` argument of `onUpdate` does not reflect the direct caller. The `setState` instead is bound early to the type of the initial function in the chain and preserved through the call chain.

This effectively reduces the usefulness of the `onUpdate` function as well as the integration with the redux devtools.
