### ISSUE TITLE
[constate] Missing Provider

### ISSUE THREAD

**Issue by gnimmelf** [diegohaz/constate#60]
Hello.

I read in the documentation that

> Constate exports a single method called createContainer. It receives two arguments: useValue and createInputs (optional). And returns { Context, Provider }.

So, without too much insight into `hooks`, I assumed that the `Provider` returned was interchangeable with Reacts `Context.Provider`. Therefor i tried using it as a static [Class.contextType](https://reactjs.org/docs/context.html#classcontexttype). -This does not work, as the `Provider` returned is just a `proxy` that warns "[constate] Missing Provider".

Reading the closed [RFC: Hooks](https://github.com/diegohaz/constate/issues/47) issue, I am wondering if what I am trying to achieve (working with a huge legacy code base), is doable with Constate?

I am sorry for the vague question, I am racing through my options due to timelimits, trying to gather as much intel as possible.

**Comment by diegohaz** [comment]
Hey @gnimmelf 

I didn't test it that way, but I'm pretty sure you can use `contextType = Container.Context`, but you do need to wrap your components with `Container.Provider`.

**Comment by gnimmelf** [comment]
Yup, it does on the sandbox...

I did wrap it in the Provider, but I will review my code.

Thank you for the swift reply.

**Comment by diegohaz** [comment]
Often, I put the Provider inside the component using the context instead of wrapping it, like this:
```jsx
class Button extends React.Component {
  static contextType = Context;
  render() {
    return (
      <Context.Provider>
        ...
      </Context.Provider>
    );
  }
}
```
It doesn't work. I don't know if that's your problem though.

**Comment by gnimmelf** [comment]
Problem was needing to wrap with Provider two places due to react-router v3; `getComponent`, *and* `getChildRoutes`, I had only wrapped the routes-file, not the "index"-component, hence 'no provider' was correct! - As I said, legacy and time =P

Thanks again.
