### ISSUE TITLE
Broswer Support

### ISSUE THREAD

**Issue by jas99** [diegohaz/constate#65]
Hey @diegohaz 

Do I need GoogleChrome/proxy-polyfill for IE9 support?

Thx

**Comment by diegohaz** [comment]
Hey. Yes, currently you do.

Alternatively, I'm thinking about using the proxy only when in development (process.env.NODE_ENV === "development").

**Comment by jas99** [comment]
Thx

**Comment by jas99** [comment]
@diegohaz 
Is there easy way to implement this container concept without using proxy?

**Comment by diegohaz** [comment]
The proxy is there only for debugging purposes. Because it's really common to forget to use the Provider. We can do this so it's only used in development mode:
```ts
const defaultValue = process.env.NODE_ENV === "development"
  ? new Proxy({}, { get: warnNoProvider, apply: warnNoProvider })
  : null;
const Context = React.createContext<V>(defaultValue as V);
```
What do you think?

**Comment by jas99** [comment]
@diegohaz I think it makes complete sense

**Comment by leonardodino** [comment]
I second that! (:
along maybe with a mini check to see if `Proxy` does exist.

never tested, but saw a bunch of articles of v8 deoptmizing the whole tree when it encounters a `Proxy`. Which makes some sense, as it can override a bunch of language behaviors.
