### ISSUE TITLE
CodeSandbox issue

### ISSUE THREAD

**Issue by AjaxSolutions** [diegohaz/constate#66]
I'm not able to use the demo, please help.

https://codesandbox.io/s/github/diegohaz/constate/tree/master/examples/counter?module=/App.js

I'm seeing an error:

TypeError
(0 , _react.useState) is not a function

**Comment by kingdaro** [comment]
React released a `16.7.0` version without hooks, which is the latest match for `^16.7.0-alpha.2` due to the `^`. Updating from that version breaks the app. The solution is to hard lock the versions in package.json:
```json
    "react": "16.7.0-alpha.2",
    "react-dom": "16.7.0-alpha.2"
```

**Comment by diegohaz** [comment]
Oh, good catch. Thank you. Fixing asap.

**Comment by diegohaz** [comment]
Fixed.
