### ISSUE TITLE
Can I update app state (global) from onMount in another component?

### ISSUE THREAD

**Issue by ripern** [diegohaz/constate#67]
The following code will just update the component MyView's state. I want to update app's state, but how? If I put an onMount on the app container (context="app") it will never be run since it's not the first being called as by design (and in your documentation).

```js
const onMount = async ({ state, setState }) => {
  try {
    doSomething()
  } catch (error) {
     setState({ showSnackbar: true, snackbarMessage: error.msg })
  }
}

const ConnectedMyView = props => (
  <Container context="myview" onMount={({ state, setState }) => onMount({ state, setState })}>
    {() => (
      <Container context="app">
        {({ foo }) => (
          <MyView foo={foo} {...props}/>
        )}
      </Container>
    )}
  </Container>
)
```

**Comment by diegohaz** [comment]
What do you want to update in app's state? Swapping containers doesn't work?

**Comment by ripern** [comment]
I want to update a snackbar message and show it. The snackbar being declared in App. The thing about onMount not being executed more than once per context is what I tried to mention in first post. However, I solved it by declaring an effect in the app container. To pass it to the myview container I also had to swap the containers (obviously) like you suggested. 

```
const appEffects = {
  showError: () => ({ setState }) => {
    setState({ showSnackbar: true, snackbarMessage: 'Could not update view' })
  },
}

const onMount = async ({ showError }) => {
  try {
    doSomething()
  } catch (error) {
    showWalletError()
  }
}

const ConnectedMyView = props => (
  <StateContainer context="app" effects={appEffects}>
    {({ showError }) => (
    <StateContainer context="myview" onMount={() => onMount({ showError })}>
      {(foo) => (
      <MyView foo={foo} {...props}/>
      )}
    </StateContainer>
  )}
  </StateContainer>
)
```

Thanks for your quick response!
Btw, do you think React Hooks will replace constate?

**Comment by diegohaz** [comment]
> Btw, do you think React Hooks will replace constate?

The current `v1 alpha` is built with Hooks in mind. I talked about it here: https://github.com/diegohaz/constate/blob/master/MIGRATING_FROM_V0_TO_V1.md#why-did-the-api-change
