### ISSUE TITLE
Provide "name" option for easier debugging

### ISSUE THREAD

**Issue by TobiasWalle** [diegohaz/constate#79]
Currently if you create a hook with this library and debug it with the React Devtools, the Provider is just called `Provider` and the Context is just called `Context` (The screenshot is from the CodeSandbox example). This can be confusing if you have many context hooks.

![image](https://user-images.githubusercontent.com/9933601/58036263-f7569400-7b2a-11e9-9eb4-3443e33b4486.png)

I propose an option, which allows the user to define a name. This name could be used to prefix the Provider and Context. Example:

```javascript
const useCounterContext = createUseContext(useCounter, { name: 'counter' });
```

In this case the name of the Provider could be `CounterProvider` and of the Context `CounterContext` (by using [displayName](https://reactjs.org/docs/react-component.html#displayname) in the library).

If you are interested, I could create a PR for this.

**Comment by diegohaz** [comment]
Does setting `useCounterContext.Provider.displayName` work?
```jsx
const useCounterContext = createUseContext(useCounter);
useCounterContext.Provider.displayName = "CounterProvider";
```
The second parameter of the `createUseContext` function is already in use, but I think we could try to extract the first function name.

**Comment by TobiasWalle** [comment]
> The second parameter of the `createUseContext` function is already in use, but I think we could try to extract the first function name:
> 
> ```js
> `${useCounter.name.replace("use", "")}Provider`
> ```

That's a great idea! This way we would avoid the duplicated name.

**Comment by TobiasWalle** [comment]
If I think about it
 
```javascript
`${useCounter.name}.Provider`
```

would be even better. As this is the way that the component is used.
