### ISSUE TITLE
Can i use this as replacement of redux?

### ISSUE THREAD

**Issue by dehamzah** [diegohaz/constate#81]
As the title said, can i use this over redux?
Can constate used for big apps?
What limitation constate bring over popular state management like redux?

**Comment by diegohaz** [comment]
You can use it as a replacement for redux, and it's suitable for bigger apps.

But they have different approaches. 

With redux, you have a single store at the top of your component tree where all your app's state lives. Whenever you want to access/update the state, you should connect to that store.

With Constate, you'll have multiple contexts provided at different levels of your component tree (depending on each components use them). Also, it's a seamlessly migration from local state (with React hooks) to shared ones, which is not supported by Redux (so easily).
