### ISSUE TITLE
eslint warning: 'React.useMemo' is called conditionally

### ISSUE THREAD

**Issue by hua-lu** [diegohaz/constate#90]
after installing 'eslint-plugin-react-hooks', a warning is reported saying:  
'React.useMemo' is called conditionally  
in this line,  
```
const memoizedValue = createMemoInputs
      ? React.useMemo(() => value, createMemoInputs(value))
      : value;
```

**Comment by diegohaz** [comment]
You should just ignore `node_modules` on your eslint configuration. `createMemoInputs` will not change between renders, as it's passed to `createUseContext` as an argument, so it's safe to `useMemo` conditionally there.
https://github.com/diegohaz/constate/blob/0248236ad500c24a7ac026b7e214278bab63392c/src/index.tsx#L26-L29
